/*! \file */
/**
 * @file linkedlist.c
 * @author Copyright (C) 2016 by Tim Fenlon
 * @date 16 November 2016
 * @brief Header for linked list node, singly linked list
 */
#include "linkedlist.h"
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

int	createNumRandomNodes(NodeList* node_list)
{
	int iNumNodes = 0;
	int result = 0;

	printf("Enter number of nodes to create?: ");
    #if defined(TARGET_WIN32)
        retVal = scanf_s("%d", &iNumNodes);
    #elif defined(TARGET_UNIX)
        result = scanf("%d", &iNumNodes);
    #elif defined(TARGET_OSX)
        result = scanf("%d", &iNumNodes);
    #endif
	if (result == EOF)
	{
		printf("EOF reached with no value");
		return 0;
	}
	else if (result < 0) {
		printf("some input error occurred");
		return 0;
	}
	else if (result == 0) {
		printf("some input error occurred");
		return 0;
	}
	else {
		printf("User requested (%d) nodes be created\n", iNumNodes);
		//Create number of nodes with node value generated by random operator
		time_t t;

		/* Intializes random number generator */
		srand((unsigned)time(&t));

		/* create linked list nodes from zero to iNumNodes */
		for (size_t i = 0; i < iNumNodes; i++)
		{
			printf("Adding node[%zd] = %d\n", i, rand() );
		}
	}

	return 1;
}

int	printAllLinkedListNodes(NodeList* node_list)
{
	printf("Selected printAllLinkedListNodes()\n\n");
	return 1;
}

int	printAllLinkedListNodesRecursive(NodeList* node_list)
{
	printf("Selected printAllLinkedListNodesRecursive()\n\n");
	return 1;
}

int	deleteAllLinkedListNodes(NodeList* node_list)
{
	printf("Selected deleteAllLinkedListNodes()\n\n");
	return 1;
}

int	deleteAllLinkedListNodesRecursive(NodeList* node_list)
{
	printf("Selected deleteAllLinkedListNodesRecursive()\n\n");
	return 1;
}
